title = "Heyo"
theme = "heyo"
baseURL = "/"
languageCode = "en"
DefaultContentLanguage = "en"
summarylength = 100
enableEmoji = true
enableRobotsTXT = true
paginate = 10

[Languages]
  [Languages.en]
    contentDir = "content/en"
    weight = 1
    LanguageName = "en"

  [Languages.pt-br]
    contentDir = "content/pt-br"
    weight = 2
    LanguageName = "pt-br"

# Enable Disqus
# disqusShortname = ""

# Google Analytics
# googleAnalytics = "UA-123-45"

[params]
  title = "I'm Jane Doe"
  author = "Jane Doe"
  description = "Call me Jane"
  profilePicture = "images/profile.png"
  keywords = ""
  favicon = "favicons/"
  customCss = []
  customJs = []
  mainSections = ["post"]
  displayMode = "dark"

# Sketch settings
## you can also enable or disable it per page
[params.sketch] 
  enable = true 
  displayOptions = true
  # use = "Graph" # Graph, Digital Rain, or Circles
  # use = "Digital Rain" # Graph, or Digital Rain
  use = "Circles"

## Math settings
[params.math]
  enable = true # global support, you can use configure it per page
  use = "mathjax" # katex or mathjax, default is mathjax

## Social links
[[params.socialIcons]]
icon = "fa-linkedin" # Font-awesome icon
title = "Linkedin"
url = "https://linkedin.com/"

[[params.socialIcons]]
icon = "fa-github"
title = "GitHub"
url = "https://github.com/lucasVadilho/lucas-anatole/"

[[params.socialIcons]]
icon = "fa-instagram"
title = "instagram"
url = "https://www.instagram.com/"

[[params.socialIcons]]
icon = "fa-envelope"
title = "e-mail"
url = "mailto:lucas.vadilho@gmail.com"

## Menu items
[menu]
[[Languages.en.menu.main]]
name = "Home"
identifier = "home"
weight = 100
url = "/"

[[Languages.en.menu.main]]
name = "Posts"
weight = 200
identifier = "posts"
url = "/post/"

[[Languages.en.menu.main]]
name = "About"
weight = 300
identifier = "about"
url = "/about/"

[[Languages.pt-br.menu.main]]
name = "Home"
identifier = "home"
weight = 100
url = "/pt-br/"

[[Languages.pt-br.menu.main]]
name = "Blog"
weight = 200
identifier = "posts"
url = "/post/"

[[Languages.pt-br.menu.main]]
name = "Sobre"
weight = 300
identifier = "about"
url = "/about/"

[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.tableOfContents]
    endLevel = 6
    startLevel = 2
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "dracula"
    tabWidth = 4

# Hugo will ignore these files, .rmd and .rmarkdown are taken care by blogdown
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown", "_files$", "_cache$"]